name: Deploy

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.7
      - name: Install dependencies
        run: python -m pip install --upgrade pip
        run: pip install -r requirements.txt
        run: pip install -r requirements_ci.txt
      - name: Run tests with pytest
        run: pytest 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: upload to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: "johnkoestner@outlook.com"
        env:
          HD_IEX_API_LIVE: ${{secrets.IEX_API_LIVE}}
          HD_IEX_API_SANDBOX: ${{secrets.IEX_API_SANDBOX}}
          HD_ALPHAVANTAGE_API: ${{secrets.ALPHAVANTAGE_API}}
          HD_AWS_TX_FILE: ${{secrets.AWS_TX_FILE}}
          